### ISSUE TITLE
crash after capture image or choose it from gallery

### ISSUE THREAD

**Issue by besho** [imgly/imgly-sdk-android-demo#12]
08-11 11:37:10.343 29075-29075/com.photoeditorsdk.android.app E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                Process: com.photoeditorsdk.android.app, PID: 29075
                                                                                java.lang.RuntimeException: Unable to start activity ComponentInfo{com.photoeditorsdk.android.app/ly.img.android.ui.activities.PhotoEditorActivity}: android.view.InflateException: Binary XML file line #10: Error inflating class ly.img.android.sdk.views.EditorPreview
                                                                                    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2411)
                                                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2474)
                                                                                    at android.app.ActivityThread.access$800(ActivityThread.java:144)
                                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1359)
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                    at android.os.Looper.loop(Looper.java:155)
                                                                                    at android.app.ActivityThread.main(ActivityThread.java:5721)
                                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                                    at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1029)
                                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:824)
                                                                                 Caused by: android.view.InflateException: Binary XML file line #10: Error inflating class ly.img.android.sdk.views.EditorPreview
                                                                                    at android.view.LayoutInflater.createView(LayoutInflater.java:633)
                                                                                    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743)
                                                                                    at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
                                                                                    at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
                                                                                    at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
                                                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
                                                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
                                                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
                                                                                    at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:407)
                                                                                    at android.app.Activity.setContentView(Activity.java:2159)
                                                                                    at ly.img.android.ui.activities.PhotoEditorActivity.onCreate(PhotoEditorActivity.java:70)
                                                                                    at android.app.Activity.performCreate(Activity.java:5961)
                                                                                    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1129)
                                                                                    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2364)
                                                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2474) 
                                                                                    at android.app.ActivityThread.access$800(ActivityThread.java:144) 
                                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1359) 
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                    at android.os.Looper.loop(Looper.java:155) 
                                                                                    at android.app.ActivityThread.main(ActivityThread.java:5721) 
                                                                                    at java.lang.reflect.Method.invoke(Native Method) 
                                                                                    at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1029) 
                                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:824) 
                                                                                 Caused by: java.lang.reflect.InvocationTargetException
                                                                                    at java.lang.reflect.Constructor.newInstance(Native Method)
                                                                                    at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
                                                                                    at android.view.LayoutInflater.createView(LayoutInflater.java:607)
                                                                                    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743) 
                                                                                    at android.view.LayoutInflater.rInflate(LayoutInflater.java:806) 
                                                                                    at android.view.LayoutInflater.rInflate(LayoutInflater.java:809) 
                                                                                    at android.view.LayoutInflater.rInflate(LayoutInflater.java:809) 
                                                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:504) 
                                                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:414) 
                                                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:365) 
                                                                                    at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:407) 
                                                                                    at android.app.Activity.setContentView(Activity.java:2159) 
                                                                                    at ly.img.android.ui.activities.PhotoEditorActivity.onCreate(PhotoEditorActivity.java:70) 
                                                                                    at android.app.Activity.performCreate(Activity.java:5961) 
                                                                                    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1129) 
                                                                                    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2364) 
                                                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2474) 
                                                                                    at android.app.ActivityThread.access$800(ActivityThread.java:144) 
                                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1359) 
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                    at android.os.Looper.loop(Looper.java:155) 
                                                                                    at android.app.ActivityThread.main(ActivityThread.java:5721) 
                                                                                    at java.lang.reflect.Method.invoke(Native Method) 
                                                                                    at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1029) 
                                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:824) 
                                                                                 Caused by: android.view.InflateException: Binary XML file line #10: Error inflating class ly.img.android.sdk.views.PaintPreviewView
                                                                                    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:757)
                                                                                    at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
                                                                                    at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
                                                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:479)
                                                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
                                                                                    at ly.img.android.sdk.views.EditorPreview.<init>(EditorPreview.java:106)
                                                                                    at java.lang.reflect.Constructor.newInstance(Native Method) 
                                                                                    at java.lang.reflect.Constructor.newInstance(Constructor.java:288) 
                                                                                    at android.view.LayoutInflater.createView(LayoutInflater.java:607) 
                                                                                    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743) 
                                                                                    at android.view.LayoutInflater.rInflate(LayoutInflater.java:806) 
                                                                                    at android.view.LayoutInflater.rInflate(LayoutInflater.java:809) 
                                                                                    at android.view.LayoutInflater.rInflate(LayoutInflater.java:809) 
                                                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:504) 
                                                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:414) 
                                                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:365) 
                                                                                    at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:407) 
                                                                                    at android.app.Activity.setContentView(Activity.java:2159) 
                                                                                    at ly.img.android.ui.activities.PhotoEditorActivity.onCreate(PhotoEditorActivity.java:70) 
                                                                                    at android.app.Activity.performCreate(Activity.java:5961) 
                                                                                    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1129) 
                                                                                    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2364) 
                                                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2474) 
                                                                                    at android.app.ActivityThread.access$800(ActivityThread.java:144) 
                                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1359) 
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                    at android.os.Looper.loop(Looper.java:155) 
                                                                                    at android.app.ActivityThread.main(ActivityThread.java:5721) 
                                                                                    at java.lang.reflect.Method.invoke(Native Method) 
                                                                                    at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1029) 
                                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:824) 
                                                                                 Caused by: java.lang.ClassNotFoundException: Didn't find class "ly.img.android.sdk.views.PaintPreviewView" on path: DexPathList[[zip file "/data/app/com.photoeditorsdk.android.app-1/base.apk"],nativeLibraryDirectories=[/data/app/com.photoeditorsdk.android.app-1/lib/arm, /vendor/lib, /system/lib]]
                                                                                    at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                                    at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                                                    at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                                                    at android.view.LayoutInflater.createView(LayoutInflater.java:571)
                                                                                    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743)
                                                                                    at android.view.LayoutInflater.rInflate(LayoutInflater.java:806) 
                                                                                    at android.view.LayoutInflater.rInflate(LayoutInflater.java:809) 
                                                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:479) 
                                                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:414) 
                                                                                    at ly.img.android.sdk.views.EditorPreview.<init>(EditorPreview.java:106) 
                                                                                    at java.lang.reflect.Constructor.newInstance(Native Method) 
                                                                                    at java.lang.reflect.Constructor.newInstance(Constructor.java:288) 
                                                                                    at android.view.LayoutInflater.createView(LayoutInflater.java:607) 
                                                                                    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743) 
                                                                                    at android.view.LayoutInflater.rInflate(LayoutInflater.java:806) 
                                                                                    at android.view.LayoutInflater.rInflate(LayoutInflater.java:809) 
                                                                                    at android.view.LayoutInflater.rInflate(LayoutInflater.java:809) 
                                                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:504) 
                                                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:414) 
                                                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:365) 
                                                                                    at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:407) 
                                                                                    at android.app.Activity.setContentView(Activity.java:2159) 
                                                                                    at ly.img.android.ui.activities.PhotoEditorActivity.onCreate(PhotoEditorActivity.java:70) 
                                                                                    at android.app.Activity.performCreate(Activity.java:5961) 
                                                                                    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1129) 
                                                                                    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2364) 
                                                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2474) 
                                                                                    at android.app.ActivityThread.access$800(ActivityThread.java:144) 
                                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1359) 
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                    at android.os.Looper.loop(Looper.java:155) 
                                                                                    at android.app.ActivityThread.main(ActivityThread.java:5721) 
                                                                                    at java.lang.reflect.Method.invoke(Native Method) 
                                                                                    at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1029) 
                                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:824) 
                                                                                	Suppressed: java.lang.ClassNotFoundException: ly.img.android.sdk.views.PaintPreviewView
                                                                                    at java.lang.Class.classForName(Native Method)
                                                                                    at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                                                                    at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                                                                    at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                                                                                    		... 34 more
                                                                                 Caused by: java.lang.NoClassDefFoundError: Class not found using th
08-11 11:37:12.466 29075-29075/com.photoeditorsdk.android.app D/Process: killProcess, pid=29075
08-11 11:37:12.466 29075-29075/com.photoeditorsdk.android.app D/Process: com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException:138 java.lang.ThreadGroup.uncaughtException:693 java.lang.ThreadGroup.uncaughtException:690 
08-11 11:37:12.746 29565-29565/com.photoeditorsdk.android.app E/SensorManager: uid = 10515
08-11 11:37:12.766 29565-29584/com.photoeditorsdk.android.app D/libc: [NET] android_getaddrinfofornet+,hn 22(0x7777772e70686f),sn(),hints(known),family 0,flags 4
08-11 11:37:12.766 29565-29584/com.photoeditorsdk.android.app D/libc: [NET] android_getaddrinfofornet-, err=8
08-11 11:37:12.776 29565-29584/com.photoeditorsdk.android.app D/libc: [NET] android_getaddrinfofornet+,hn 22(0x7777772e70686f),sn(),hints(known),family 0,flags 1024
08-11 11:37:12.776 29565-29584/com.photoeditorsdk.android.app D/libc: [NET] android_getaddrinfofornet-, pass to proxy
08-11 11:37:12.776 29565-29584/com.photoeditorsdk.android.app D/libc: [NET] android_getaddrinfo_proxy+
08-11 11:37:12.776 29565-29584/com.photoeditorsdk.android.app D/libc: [NET] android_getaddrinfo_proxy get netid:0

**Comment by svendvd** [comment]
Fixed in v2.0.11 RC1
