### ISSUE TITLE
App Crash on prelollipop

### ISSUE THREAD

**Issue by jefrisingh** [imgly/imgly-sdk-android-demo#16]
09-15 05:26:53.854 458-502/com.photoeditorsdk.android.app E/AndroidRuntime: FATAL EXCEPTION: Thread-203
                                                                            Process: com.photoeditorsdk.android.app, PID: 458
                                                                            android.support.v8.renderscript.RSRuntimeException: Loading of ScriptC script failed.
                                                                                at android.support.v8.renderscript.ScriptC.<init>(ScriptC.java:61)
                                                                                at ly.img.android.ScriptC_translate_3d_lut.<init>(ScriptC_translate_3d_lut.java:42)
                                                                                at ly.img.android.ScriptC_translate_3d_lut.<init>(ScriptC_translate_3d_lut.java:34)
                                                                                at ly.img.android.sdk.filter.LutColorFilter.getLutCube(LutColorFilter.java:361)
                                                                                at ly.img.android.sdk.filter.LutColorFilter.getLutCube(LutColorFilter.java:324)
                                                                                at ly.img.android.sdk.filter.LutColorFilter.getLutRenderScript(LutColorFilter.java:196)
                                                                                at ly.img.android.sdk.filter.LutColorFilter.renderImage(LutColorFilter.java:257)
                                                                                at ly.img.android.sdk.filter.LutColorFilter.renderImage(LutColorFilter.java:279)
                                                                                at ly.img.android.sdk.filter.LutColorFilter.getThumbnailBitmap(LutColorFilter.java:169)
                                                                                at ly.img.android.sdk.configuration.AbstractConfig.getThumbnailBitmap(AbstractConfig.java:215)
                                                                                at ly.img.android.sdk.configuration.AbstractConfig.generateBindDataAsync(AbstractConfig.java:120)
                                                                                at ly.img.android.sdk.configuration.AbstractConfig.generateBindDataAsync(AbstractConfig.java:40)
                                                                                at ly.img.android.ui.adapter.DataSourceListAdapter$LoaderList.runEntryProcess(DataSourceListAdapter.java:272)
                                                                                at ly.img.android.ui.adapter.DataSourceListAdapter$LoaderList$Task.run(DataSourceListAdapter.java:316)

while trying to access Filter menu on kitkat mobile, but it's working fine in API level 20+

**Comment by svendvd** [comment]
Fixed in v2.0.11 RC1
