### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException: length=65536; index=65536

### ISSUE THREAD

**Issue by divysoni3** [imgly/imgly-sdk-android-demo#2]
> I am getting crash when I open effect, please fix this code

`FATAL EXCEPTION: Thread-231969
                                                                                        Process: com.mobisoftsol.camerawitheffectsample, PID: 21158
                                                                                        java.lang.ArrayIndexOutOfBoundsException: length=65536; index=65536
                                                                                            at ly.img.android.sdk.filter.LutColorFilter.getLutCube(LutColorFilter.java:272)
                                                                                            at ly.img.android.sdk.filter.LutColorFilter.getLutCube(LutColorFilter.java:240)
                                                                                            at ly.img.android.sdk.filter.LutColorFilter.getRsScript(LutColorFilter.java:147)
                                                                                            at ly.img.android.sdk.filter.LutColorFilter.renderImage(LutColorFilter.java:161)
                                                                                            at ly.img.android.sdk.filter.LutColorFilter.renderImage(LutColorFilter.java:181)
                                                                                            at ly.img.android.sdk.filter.LutColorFilter.getThumbnailBitmap(LutColorFilter.java:130)
                                                                                            at ly.img.android.sdk.configuration.AbstractConfig.getThumbnailBitmap(AbstractConfig.java:187)
                                                                                            at ly.img.android.sdk.configuration.AbstractConfig.generateBindDataAsync(AbstractConfig.java:92)
                                                                                            at ly.img.android.sdk.configuration.AbstractConfig.generateBindDataAsync(AbstractConfig.java:24)
                                                                                            at ly.img.android.ui.adapter.DataSourceListAdapter$LoaderList.runEntryProcess(DataSourceListAdapter.java:235)
                                                                                            at ly.img.android.ui.adapter.DataSourceListAdapter$LoaderList$Task.run(DataSourceListAdapter.java:219)
03-28 17:51:56.519 21158-22218/com.mobisoftsol.camerawitheffectsample I/Process: Sending signal. PID: 21158 SIG: 9
`

**Comment by K4stor** [comment]
Are you running the example app ? What device are you using ? 
Please provide more information

**Comment by divysoni3** [comment]
I am using Moto G3 with marshmallow version. I am getting same crash in your app (ImgLy Editor) also.

**Comment by svendvd** [comment]
Hello, did you use a custom lut? 
If so, please make sure that the LUT resolution is 512x512px and only placed in the drawable-nodpi folder.

**Comment by divysoni3** [comment]
I am not using any custom lut. when i open app camera preview is displayed, when i click on lower right button for see the filters list then I am getting this crash.

**Comment by divysoni3** [comment]
I found the bug. It was because of this method.
limitMemoryUsage(opts);
