### ISSUE TITLE
Cannot run sample app

### ISSUE THREAD

**Issue by IbraTq** [imgly/imgly-sdk-android-demo#21]
I cannot run sample application.
Please check this log
Thanks

FATAL EXCEPTION: main
                                                                              Process: com.photoeditorsdk.android.app, PID: 2742
                                                                              java.lang.RuntimeException: Unable to start activity ComponentInfo{com.photoeditorsdk.android.app/ly.img.android.ui.activities.CameraPreviewActivity}: java.lang.RuntimeException: StateClass: "class ly.img.android.sdk.models.state.ImgLyConfig" has no default constructor
                                                                                  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2325)
                                                                                  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
                                                                                  at android.app.ActivityThread.access$800(ActivityThread.java:151)
                                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                  at android.os.Looper.loop(Looper.java:135)
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:5254)
                                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                                  at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
                                                                               Caused by: java.lang.RuntimeException: StateClass: "class ly.img.android.sdk.models.state.ImgLyConfig" has no default constructor
                                                                                  at ly.img.android.sdk.models.state.manager.StateHandler.getStateModel(StateHandler.java:172)
                                                                                  at ly.img.android.ui.activities.ImgLyActivity.getConfig(ImgLyActivity.java:54)
                                                                                  at ly.img.android.ui.activities.CameraPreviewActivity.onCreate(CameraPreviewActivity.java:97)
                                                                                  at android.app.Activity.performCreate(Activity.java:5990)
                                                                                  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
                                                                                  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
                                                                                  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387) 
                                                                                  at android.app.ActivityThread.access$800(ActivityThread.java:151) 
                                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303) 
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                  at android.os.Looper.loop(Looper.java:135) 
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:5254) 
                                                                                  at java.lang.reflect.Method.invoke(Native Method) 
                                                                                  at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903) 
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

**Comment by svendvd** [comment]
We have released v2.0.13 this problem should be fixed.
