### ISSUE TITLE
sometimes app crashes while selecting image from gallery v2.0.12RC2

### ISSUE THREAD

**Issue by satendra02** [imgly/imgly-sdk-android-demo#25]
Steps to reproduce.
1. open app -> capture image and edit it.
2. open app -> chose gallery option on CameraPreviewActivity -> select image from gallery -> app crashes

    10-26 13:45:30.226 22073-22073/com.creative.kettl E/AndroidRuntime: FATAL EXCEPTION: main
                                                                    Process: com.creative.kettl, PID: 22073
                                                                    java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1, result=-1, data=Intent { dat=content://media/external/images/media/26036 flg=0x1 }} to activity {com.creative.kettl/ly.img.android.ui.activities.CameraPreviewActivity}: java.util.ConcurrentModificationException
                                                                        at android.app.ActivityThread.deliverResults(ActivityThread.java:3659)
                                                                        at android.app.ActivityThread.handleSendResult(ActivityThread.java:3702)
                                                                        at android.app.ActivityThread.access$1300(ActivityThread.java:155)
                                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1366)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                        at android.os.Looper.loop(Looper.java:135)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:5343)
                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                        at java.lang.reflect.Method.invoke(Method.java:372)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)
                                                                     Caused by: java.util.ConcurrentModificationException
                                                                        at java.util.HashMap$HashIterator.nextEntry(HashMap.java:787)
                                                                        at java.util.HashMap$KeyIterator.next(HashMap.java:814)
                                                                        at ly.img.android.sdk.models.state.manager.StateHandler.onStateChangeEvent(StateHandler.java:87)
                                                                        at ly.img.android.sdk.models.state.manager.StateListenerInterfaceWrapper.onStateChangeEvent(StateListenerInterfaceWrapper.java:16)
                                                                        at ly.img.android.sdk.models.state.manager.StateListener.onPropertyChanged(StateListener.java:13)
                                                                        at android.databinding.PropertyChangeRegistry$1.onNotifyCallback(PropertyChangeRegistry.java:28)
                                                                        at android.databinding.PropertyChangeRegistry$1.onNotifyCallback(PropertyChangeRegistry.java:24)
                                                                        at android.databinding.CallbackRegistry.notifyCallbacks(CallbackRegistry.java:201)
                                                                        at android.databinding.CallbackRegistry.notifyFirst64(CallbackRegistry.java:122)
                                                                        at android.databinding.CallbackRegistry.notifyRemainder(CallbackRegistry.java:169)
                                                                        at android.databinding.CallbackRegistry.notifyRecurse(CallbackRegistry.java:145)
                                                                        at android.databinding.CallbackRegistry.notifyCallbacks(CallbackRegistry.java:91)
                                                                        at android.databinding.BaseObservable.notifyPropertyChanged(BaseObservable.java:62)
                                                                        at ly.img.android.sdk.models.state.manager.StateObservable.notifyPropertyChanged(StateObservable.java:120)
                                                                        at ly.img.android.sdk.models.state.EditorLoadSettings.setImageSourcePath(EditorLoadSettings.java:92)
                                                                        at ly.img.android.ui.activities.CameraPreviewActivity.onActivityResult(CameraPreviewActivity.java:356)
                                                                        at android.app.Activity.dispatchActivityResult(Activity.java:6218)
                                                                        at android.app.ActivityThread.deliverResults(ActivityThread.java:3655)
                                                                        at android.app.ActivityThread.handleSendResult(ActivityThread.java:3702) 
                                                                        at android.app.ActivityThread.access$1300(ActivityThread.java:155) 
                                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1366) 
                                                                        at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                        at android.os.Looper.loop(Looper.java:135) 
                                                                        at android.app.ActivityThread.main(ActivityThread.java:5343) 
                                                                        at java.lang.reflect.Method.invoke(Native Method) 
                                                                        at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905) 
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700) `

**Comment by maltebaumann** [comment]
Hi Satendra,
thanks for the report. We're aware of the issue and are working on a fix. There will be a new version in a few days.

**Comment by svendvd** [comment]
We have released v2.0.13 your problem should be fixed.
