### ISSUE TITLE
Unable to Open Editor

### ISSUE THREAD

**Issue by achavhan** [imgly/imgly-sdk-android-demo#29]
`11-03 11:28:17.960 15946-15946/oasis.crm E/AndroidRuntime: FATAL EXCEPTION: main
                                                           Process: oasis.crm, PID: 15946
                                                           java.lang.RuntimeException: Unable to start activity ComponentInfo{oasis.crm/ly.img.android.ui.activities.PhotoEditorActivity}: android.view.InflateException: Binary XML file line #24: Binary XML file line #24: Error inflating class ly.img.android.sdk.views.EditorPreview
                                                               at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2655)
                                                               at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2725)
                                                               at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1572)
                                                               at android.os.Handler.dispatchMessage(Handler.java:111)
                                                               at android.os.Looper.loop(Looper.java:207)
                                                               at android.app.ActivityThread.main(ActivityThread.java:5896)
                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
                                                            Caused by: android.view.InflateException: Binary XML file line #24: Binary XML file line #24: Error inflating class ly.img.android.sdk.views.EditorPreview
                                                               at android.view.LayoutInflater.inflate(LayoutInflater.java:539)
                                                               at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
                                                               at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
                                                               at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:410)
                                                               at android.app.Activity.setContentView(Activity.java:2209)
                                                               at ly.img.android.ui.activities.PhotoEditorActivity.onCreate(PhotoEditorActivity.java:59)
                                                               at android.app.Activity.performCreate(Activity.java:6298)
                                                               at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1113)
                                                               at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2608)
                                                               at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2725) 
                                                               at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1572) 
                                                               at android.os.Handler.dispatchMessage(Handler.java:111) 
                                                               at android.os.Looper.loop(Looper.java:207) 
                                                               at android.app.ActivityThread.main(ActivityThread.java:5896) 
                                                               at java.lang.reflect.Method.invoke(Native Method) 
                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789) 
                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679) 
                                                            Caused by: android.view.InflateException: Binary XML file line #24: Error inflating class ly.img.android.sdk.views.EditorPreview
                                                               at android.view.LayoutInflater.createView(LayoutInflater.java:645)
                                                               at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:764)
                                                               at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
                                                               at android.view.LayoutInflater.rInflate(LayoutInflater.java:835)
                                                               at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
                                                               at android.view.LayoutInflater.rInflate(LayoutInflater.java:838)
                                                               at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
                                                               at android.view.LayoutInflater.rInflate(LayoutInflater.java:838)
                                                               at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
                                                               at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
                                                               at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
                                                               at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
                                                               at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:410) 
                                                               at android.app.Activity.setContentView(Activity.java:2209) 
                                                               at ly.img.android.ui.activities.PhotoEditorActivity.onCreate(PhotoEditorActivity.java:59) 
                                                               at android.app.Activity.performCreate(Activity.java:6298) 
                                                               at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1113) 
                                                               at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2608) 
                                                               at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2725) 
                                                               at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1572) 
                                                               at android.os.Handler.dispatchMessage(Handler.java:111) 
                                                               at android.os.Looper.loop(Looper.java:207) 
                                                               at android.app.ActivityThread.main(ActivityThread.java:5896) 
                                                               at java.lang.reflect.Method.invoke(Native Method) 
                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789) 
                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679) 
                                                            Caused by: java.lang.reflect.InvocationTargetException
                                                               at java.lang.reflect.Constructor.newInstance(Native Method)
                                                               at android.view.LayoutInflater.createView(LayoutInflater.java:619)
                                                               at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:764) 
                                                               at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704) 
                                                               at android.view.LayoutInflater.rInflate(LayoutInflater.java:835) 
                                                               at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) 
                                                               at android.view.LayoutInflater.rInflate(LayoutInflater.java:838) 
                                                               at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) 
                                                               at android.view.LayoutInflater.rInflate(LayoutInflater.java:838) 
                                                               at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) 
                                                               at android.view.LayoutInflater.inflate(LayoutInflater.java:515) 
                                                               at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
                                                               at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
                                                               at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:410) 
                                                               at android.app.Activity.setContentView(Activity.java:2209) 
                                                               at ly.img.android.ui.activities.PhotoEditorActivity.onCreate(PhotoEditorActivity.java:59) 
                                                               at android.app.Activity.performCreate(Activity.java:6298) 
                                                               at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1113) 
                                                               at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2608) 
                                                               at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2725) 
                                                               at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1572) 
                                                               at android.os.Handler.dispatchMessage(Handler.java:111) 
                                                               at android.os.Looper.loop(Looper.java:207) 
                                                               at android.app.ActivityThread.main(ActivityThread.java:5896) 
                                                               at java.lang.reflect.Method.invoke(Native Method) 
                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789) 
                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679) 
                                                            Caused by: android.view.InflateException: Binary XML file line #25: Binary XML file line #25: Error inflating class ly.img.android.sdk.views.PicturePreviewView
                                                               at android.view.LayoutInflater.inflate(LayoutInflater.java:539)
                                                               at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
                                                               at ly.img.android.sdk.views.EditorPreview.<init>(EditorPreview.java:132)
                                                               at java.lang.reflect.Constructor.newInstance(Native Method) 
                                                               at android.view.LayoutInflater.createView(LayoutInflater.java:619) 
                                                               at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:764) 
                                                               at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704) 
                                                               at android.view.LayoutInflater.rInflate(LayoutInflater.java:835) 
                                                               at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) 
                                                               at android.view.LayoutInflater.rInflate(LayoutInflater.java:838) 
                                                               at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) 
                                                               at android.view.LayoutInflater.rInflate(LayoutInflater.java:838) 
                                                               at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) 
                                                               at android.view.LayoutInflater.inflate(LayoutInflater.java:515) 
                                                               at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
                                                               at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
                                                               at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:410) 
                                                               at android.app.Activity.setContentView(Activity.java:2209) 
                                                               at ly.img.android.ui.activities.PhotoEditorActivity.onCreate(PhotoEditorActivity.java:59) 
                                                               at android.app.Activity.performCreate(Activity.java:6298) 
                                                               at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1113) 
                                                               at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2608) 
                                                               at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2725) 
                                                               at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1572) 
                                                               at android.os.Handler.dispatchMessage(Handler.java:111) 
                                                               at android.os.Looper.loop(Looper.java:207) 
                                                               at android.app.ActivityThread.main(ActivityThread.java:5896) 
                                                               at java.lang.reflect.Method.invoke(Native Method) 
                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789) 
                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679) 
                                                            Caused by: android.view.InflateException: Binary XML file line #25: Error inflating class ly.img.android.sdk.views.PicturePreviewView
                                                               at android.view.LayoutInflater.createView(LayoutInflater.java:645)
                                                               at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:764)
                                                               at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
                                                               at android.view.LayoutInflater.rInflate(LayoutInflater.java:835)
                                                               at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
                                                               at android.view.LayoutInflater.rInflate(LayoutInflater.java:838)
                                                               at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
                                                               at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
                                                               at ly.img.android.sdk.views.EditorPreview.<init>(EditorPreview.java:132) 
                                                               at java.lang.reflect.Constructor.newInstance(Native Method) 
                                                               at android.view.LayoutInflater.createView(LayoutInflater.java:619) 
                                                               at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:764) 
                                                               at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704) 
                                                               at android.view.LayoutInflater.rInflate(LayoutInflater.java:835) 
                                                               at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) 
                                                               at android.view.LayoutInflater.rInflate(LayoutInflater.java:838) 
                                                               at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) 
                                                               at android.view.LayoutInflater.rInflate(LayoutInflater.java:838) 
                                                               at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) 
                                                               at android.view.LayoutInflater.inflate(LayoutInflater.java:515) 
                                                               at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
                                                               at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
                                                               at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:410) 
                                                               at android.app.Activity.setContentView(Activity.java:2209) 
                                                               at ly.img.android.ui.activities.PhotoEditorActivity.onCreate(PhotoEditorActivity.java:59) 
                                                               at android.app.Activity.performCreate(Activity.java:6298) 
                                                               at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1113) 
                                                               at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2608) 
                                                               at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2725) 
                                                               at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1572) 
                                                               at android.os.Handler.dispatchMessage(Handler.java:111) 
                                                               at android.os.Looper.loop(Looper.java:207) 
                                                               at android.app.ActivityThread.main(ActivityThread.java:5896) 
                                                               at java.lang.reflect.Method.invoke(Native Method) 
                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789) 
                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679) 
                                                            Caused by: java.lang.reflect.InvocationTargetException
                                                               at java.lang.reflect.Constructor.newInstance(Native Method)
                                                               at android.view.LayoutInflater.createView(LayoutInflater.java:619)
                                                               at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:764) 
                                                               at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704) 
                                                               at android.view.LayoutInflater.rInflate(LayoutInflater.java:835) 
                                                               at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) 
                                                               at android.view.LayoutInflater.rInflate(LayoutInflater.java:838) 
                                                               at android.view.LayoutInflater.inflate(LayoutInflater.java:489) 
                                                               at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
                                                               at ly.img.android.sdk.views.EditorPreview.<init>(EditorPreview.java:132) 
                                                               at java.lang.reflect.Constructor.newInstance(Native Method) 
                                                               at android.view.LayoutInflater.createView(LayoutInflater.java:619) 
                                                               at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:764) 
                                                               at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704) 
                                                               at android.view.LayoutInflater.rInflate(LayoutInflater.java:835) 
                                                               at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) 
                                                               at android.view.LayoutInflater.rInflate(LayoutInflater.java:838) 
                                                               at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) 
                                                               at android.view.LayoutInflater.rInflate(LayoutInflater.java:838) 
                                                               at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) 
                                                               at android.view.LayoutInflater.inflate(LayoutInflater.java:515) 
                                                               at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
                                                               at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
                                                               at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:410) 
                                                               at android.app.Activity.setContentView(Activity.java:2209) 
                                                               at ly.img.android.ui.activities.PhotoEditorActivity.onCreate(PhotoEditorActivity.java:59) 
                                                               at android.app.Activity.performCreate(Activity.java:6298) 
                                                               at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1113) 
                                                               at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2608) 
                                                               at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2725) 
                                                               at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1572) 
                                                               at android.os.Handler.dispatchMessage(Handler.java:111) 
                                                               at android.os.Looper.loop(Looper.java:207) 
                                                               at android.app.ActivityThread.main(ActivityThread.java:5896) 
                                                               at java.lang.reflect.Method.invoke(Native Method) 
                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789) 
                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679) 
                                                            Caused by: java.l
`

**Comment by achavhan** [comment]
Sorry my mistake forgot to add this two lines

 /* Don't forget this two lines, otherwise the app will crash! */
        renderscriptTargetApi 23
        renderscriptSupportModeEnabled true
