### ISSUE TITLE
OperationResultHolder.setBlurResult null exception

### ISSUE THREAD

**Issue by SametGunduz** [imgly/imgly-sdk-android-demo#33]
I debug 'CustomizeLayoutExample' so take picture and save button click throw exception.

Note : Device orientation is landscape

`/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@1712d441 time:11830027
E/AndroidRuntime: FATAL EXCEPTION: Operatorly.img.android.sdk.operator.SyncedOperators@229953d0
                  Process: com.example.sametgunduz.tecdemo, PID: 21312
                  java.lang.NullPointerException: Attempt to invoke virtual method 'void ly.img.android.sdk.models.OperationResultHolder.setBlurResult(android.graphics.Bitmap)' on a null object reference
                      at ly.img.android.sdk.views.PicturePreviewView.onOperatorSyncedResult(PicturePreviewView.java:620)
                      at ly.img.android.sdk.operator.SyncedOperators$BackgroundRunner.run(SyncedOperators.java:134)
                      at ly.img.android.sdk.utils.ThreadUtils$TaskThread.doTask(ThreadUtils.java:253)
                      at ly.img.android.sdk.utils.ThreadUtils$TaskThread.run(ThreadUtils.java:236)
I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@14b9fa4e time:11830589
I/Process: Sending signal. PID: 21312 SIG: 9
Disconnected from the target VM, address: 'localhost:8614', transport: 'socket'
`

**Comment by svendvd** [comment]
Hi, 
how can I reproduce this?
