### ISSUE TITLE
Android 5.1 Crash

### ISSUE THREAD

**Issue by JigneshPatel23** [imgly/imgly-sdk-android-demo#36]
`android.support.v8.renderscript.RSRuntimeException: Loading of ScriptC script failed.
	at android.support.v8.renderscript.ScriptC.<init>(ScriptC.java:83)
	at ly.img.android.ScriptC_jpeg.<init>(ScriptC_jpeg.java:34)
	at ly.img.android.sdk.utils.ImglyJpeg.<init>(ImglyJpeg.java:57)
	at ly.img.android.sdk.operator.ImageSaveOperation.doOperation(ImageSaveOperation.java:114)
	at ly.img.android.sdk.operator.ImageSaveOperation.doOperation(ImageSaveOperation.java:45)
	at ly.img.android.sdk.operator.AbstractOperation$1.run(AbstractOperation.java:138)
	at ly.img.android.sdk.operator.ChunkIntermediary.combineChunkRequests(ChunkIntermediary.java:210)
	at ly.img.android.sdk.operator.ChunkIntermediary.combineChunkRequests(ChunkIntermediary.java:204)
	at ly.img.android.sdk.operator.AbstractOperation.runAndDelegate(AbstractOperation.java:131)
	at ly.img.android.sdk.operator.Operator.renderResultOnWorker(Operator.java:117)
	at ly.img.android.sdk.operator.Operator$BackgroundRunner.run(Operator.java:200)
	at ly.img.android.sdk.utils.ThreadUtils$TaskThread.doTask(ThreadUtils.java:253)
	at ly.img.android.sdk.utils.ThreadUtils$TaskThread.run(ThreadUtils.java:236)
 `

**Comment by svendvd** [comment]
You have a wrong combination of buildToolVersion and renderscriptTargetApi
```
compileSdkVersion 24
buildToolsVersion '24.0.3'
```

```
renderscriptTargetApi 23
renderscriptSupportModeEnabled true
```
