### ISSUE TITLE
ExceptionInInitializerError

### ISSUE THREAD

**Issue by anvesh523** [imgly/imgly-sdk-android-demo#4]
E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                java.lang.ExceptionInInitializerError
                                                                                    at ly.img.android.sdk.configuration.PhotoEditorSdkConfig.<clinit>(PhotoEditorSdkConfig.java:118)
                                                                                    at ly.img.android.ui.activities.CameraPreviewActivity.onCreate(CameraPreviewActivity.java:94)
                                                                                    at android.app.Activity.performCreate(Activity.java:5182)
                                                                                    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1081)
                                                                                    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2270)
                                                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2358)
                                                                                    at android.app.ActivityThread.access$600(ActivityThread.java:156)
                                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1340)
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                    at android.os.Looper.loop(Looper.java:153)
                                                                                    at android.app.ActivityThread.main(ActivityThread.java:5299)
                                                                                    at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                    at java.lang.reflect.Method.invoke(Method.java:511)
                                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
                                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
                                                                                    at dalvik.system.NativeStart.main(Native Method)
                                                                                 Caused by: android.support.v8.renderscript.RSRuntimeException: Error loading libRSSupport library
                                                                                    at android.support.v8.renderscript.RenderScript.internalCreate(RenderScript.java:1379)
                                                                                    at android.support.v8.renderscript.RenderScript.create(RenderScript.java:1504)
                                                                                    at android.support.v8.renderscript.RenderScript.create(RenderScript.java:1454)
                                                                                    at android.support.v8.renderscript.RenderScript.create(RenderScript.java:1430)
                                                                                    at android.support.v8.renderscript.RenderScript.create(RenderScript.java:1417)
                                                                                    at ly.img.android.ImgLySdk.getAppRsContext(ImgLySdk.java:60)
                                                                                    at ly.img.android.sdk.filter.LutColorFilter.<clinit>(LutColorFilter.java:64)
                                                                                    at ly.img.android.sdk.configuration.PhotoEditorSdkConfig.<clinit>(PhotoEditorSdkConfig.java:118) 
                                                                                    at ly.img.android.ui.activities.CameraPreviewActivity.onCreate(CameraPreviewActivity.java:94) 
                                                                                    at android.app.Activity.performCreate(Activity.java:5182) 
                                                                                    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1081) 
                                                                                    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2270) 
                                                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2358) 
                                                                                    at android.app.ActivityThread.access$600(ActivityThread.java:156) 
                                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1340) 
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                                    at android.os.Looper.loop(Looper.java:153) 
                                                                                    at android.app.ActivityThread.main(ActivityThread.java:5299) 
                                                                                    at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                                    at java.lang.reflect.Method.invoke(Method.java:511) 
                                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833) 
                                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600) 
                                                                                    at dalvik.system.NativeStart.main(Native Method)

**Comment by svendvd** [comment]
Please add Renderscript support to you Gradle file

android {
    compileSdkVersion 23
    buildToolsVersion '23.0.3'

    defaultConfig {
        ...
        renderscriptTargetApi 20
        renderscriptSupportModeEnabled true
    }
