### ISSUE TITLE
Crashes Fatal Exception: java.lang.NullPointerException        at ly.img.android.sdk.operator.ImageLoadOperation$1.run(ImageLoadOperation.java:121)

### ISSUE THREAD

**Issue by IbraTq** [imgly/imgly-sdk-android-demo#50]
HI Imgly team.
Please check this log.
I use ver 2.0.27

Fatal Exception: java.lang.NullPointerException
       at ly.img.android.sdk.operator.ImageLoadOperation$1.run(ImageLoadOperation.java:121)
       at ly.img.android.sdk.operator.ChunkIntermediary.combineChunkRequests(ChunkIntermediary.java:210)
       at ly.img.android.sdk.operator.ChunkIntermediary.combineChunkRequests(ChunkIntermediary.java:204)
       at ly.img.android.sdk.operator.ImageLoadOperation.doOperation(ImageLoadOperation.java:109)
       at ly.img.android.sdk.operator.ImageLoadOperation.getEstimatedMemoryConsumptionFactor(ImageLoadOperation.java:40)
       at ly.img.android.sdk.operator.AbstractOperation$1.run(AbstractOperation.java:138)
       at ly.img.android.sdk.operator.ChunkIntermediary.combineChunkRequests(ChunkIntermediary.java:210)
       at ly.img.android.sdk.operator.ChunkIntermediary.combineChunkRequests(ChunkIntermediary.java:204)
       at ly.img.android.sdk.operator.AbstractOperation.doOperation(AbstractOperation.java:131)
       at ly.img.android.sdk.operator.AbstractOperation.doOperation(AbstractOperation.java:168)
       at ly.img.android.sdk.operator.FilterOperation.doOperation(FilterOperation.java:55)
       at ly.img.android.sdk.operator.FilterOperation.getEstimatedMemoryConsumptionFactor(FilterOperation.java:33)
       at ly.img.android.sdk.operator.AbstractOperation$1.run(AbstractOperation.java:138)
       at ly.img.android.sdk.operator.ChunkIntermediary.combineChunkRequests(ChunkIntermediary.java:210)
       at ly.img.android.sdk.operator.ChunkIntermediary.combineChunkRequests(ChunkIntermediary.java:204)
       at ly.img.android.sdk.operator.AbstractOperation.doOperation(AbstractOperation.java:131)
       at ly.img.android.sdk.operator.AbstractOperation.doOperation(AbstractOperation.java:168)
       at ly.img.android.sdk.operator.FocusOperation.doOperation(FocusOperation.java:209)
       at ly.img.android.sdk.operator.FocusOperation.getEstimatedMemoryConsumptionFactor(FocusOperation.java:50)
       at ly.img.android.sdk.operator.AbstractOperation$1.run(AbstractOperation.java:138)
       at ly.img.android.sdk.operator.ChunkIntermediary.combineChunkRequests(ChunkIntermediary.java:210)
       at ly.img.android.sdk.operator.ChunkIntermediary.combineChunkRequests(ChunkIntermediary.java:204)
       at ly.img.android.sdk.operator.AbstractOperation.doOperation(AbstractOperation.java:131)
       at ly.img.android.sdk.operator.AbstractOperation.doOperation(AbstractOperation.java:168)
       at ly.img.android.sdk.operator.ColorAdjustmentOperation.doOperation(ColorAdjustmentOperation.java:58)
       at ly.img.android.sdk.operator.ColorAdjustmentOperation.getEstimatedMemoryConsumptionFactor(ColorAdjustmentOperation.java:37)
       at ly.img.android.sdk.operator.AbstractOperation$1.run(AbstractOperation.java:138)
       at ly.img.android.sdk.operator.ChunkIntermediary.combineChunkRequests(ChunkIntermediary.java:210)
       at ly.img.android.sdk.operator.ChunkIntermediary.combineChunkRequests(ChunkIntermediary.java:204)
       at ly.img.android.sdk.operator.AbstractOperation.doOperation(AbstractOperation.java:131)
       at ly.img.android.sdk.operator.AbstractOperation.doOperation(AbstractOperation.java:168)
       at ly.img.android.sdk.operator.FrameOperation.doOperation(FrameOperation.java:73)
       at ly.img.android.sdk.operator.FrameOperation.getEstimatedMemoryConsumptionFactor(FrameOperation.java:48)
       at ly.img.android.sdk.operator.AbstractOperation$1.run(AbstractOperation.java:138)
       at ly.img.android.sdk.operator.ChunkIntermediary.combineChunkRequests(ChunkIntermediary.java:210)
       at ly.img.android.sdk.operator.ChunkIntermediary.combineChunkRequests(ChunkIntermediary.java:204)
       at ly.img.android.sdk.operator.AbstractOperation.doOperation(AbstractOperation.java:131)
       at ly.img.android.sdk.operator.AbstractOperation.doOperation(AbstractOperation.java:168)
       at ly.img.android.sdk.operator.LayerOperation.doOperation(LayerOperation.java:72)
       at ly.img.android.sdk.operator.LayerOperation.getEstimatedMemoryConsumptionFactor(LayerOperation.java:34)
       at ly.img.android.sdk.operator.AbstractOperation$1.run(AbstractOperation.java:138)
       at ly.img.android.sdk.operator.ChunkIntermediary.combineChunkRequests(ChunkIntermediary.java:210)
       at ly.img.android.sdk.operator.ChunkIntermediary.combineChunkRequests(ChunkIntermediary.java:204)
       at ly.img.android.sdk.operator.AbstractOperation.doOperation(AbstractOperation.java:131)
       at ly.img.android.sdk.operator.AbstractOperation.doOperation(AbstractOperation.java:168)
       at ly.img.android.sdk.operator.CropOperation.doOperation(CropOperation.java:53)
       at ly.img.android.sdk.operator.CropOperation.getEstimatedMemoryConsumptionFactor(CropOperation.java:32)
       at ly.img.android.sdk.operator.AbstractOperation$1.run(AbstractOperation.java:138)
       at ly.img.android.sdk.operator.ChunkIntermediary.combineChunkRequests(ChunkIntermediary.java:210)
       at ly.img.android.sdk.operator.ChunkIntermediary.combineChunkRequests(ChunkIntermediary.java:204)
       at ly.img.android.sdk.operator.AbstractOperation.doOperation(AbstractOperation.java:131)
       at ly.img.android.sdk.operator.AbstractOperation.doOperation(AbstractOperation.java:168)
       at ly.img.android.sdk.operator.OrientationOperation.doOperation(OrientationOperation.java:52)
       at ly.img.android.sdk.operator.OrientationOperation.getEstimatedMemoryConsumptionFactor(OrientationOperation.java:34)
       at ly.img.android.sdk.operator.AbstractOperation$1.run(AbstractOperation.java:138)
       at ly.img.android.sdk.operator.ChunkIntermediary.combineChunkRequests(ChunkIntermediary.java:210)
       at ly.img.android.sdk.operator.ChunkIntermediary.combineChunkRequests(ChunkIntermediary.java:204)
       at ly.img.android.sdk.operator.AbstractOperation.doOperation(AbstractOperation.java:131)
       at ly.img.android.sdk.operator.AbstractOperation.doOperation(AbstractOperation.java:168)
       at ly.img.android.sdk.operator.ImageSaveOperation.doOperation(ImageSaveOperation.java:144)
       at ly.img.android.sdk.operator.ImageSaveOperation.getEstimatedMemoryConsumptionFactor(ImageSaveOperation.java:49)
       at ly.img.android.sdk.operator.AbstractOperation$1.run(AbstractOperation.java:138)
       at ly.img.android.sdk.operator.ChunkIntermediary.combineChunkRequests(ChunkIntermediary.java:210)
       at ly.img.android.sdk.operator.ChunkIntermediary.combineChunkRequests(ChunkIntermediary.java:204)
       at ly.img.android.sdk.operator.AbstractOperation.doOperation(AbstractOperation.java:131)
       at ly.img.android.sdk.operator.Operator.renderResultOnWorker(Operator.java:121)
       at ly.img.android.sdk.operator.Operator$BackgroundRunner.run(Operator.java:204)
       at ly.img.android.sdk.utils.ThreadUtils$TaskThread.doTask(ThreadUtils.java:253)
       at ly.img.android.sdk.utils.ThreadUtils$TaskThread.run(ThreadUtils.java:236)

**Comment by svendvd** [comment]
Please try v2.1.3
