### ISSUE TITLE
Exception: autoFocus failed

### ISSUE THREAD

**Issue by nero-tang** [imgly/imgly-sdk-android-demo#6]
Exception raised when tried to autofocus multiple times on Sony Xperia Device

``` java
java.lang.RuntimeException: autoFocus failed
     at android.hardware.Camera.native_autoFocus(Native Method)
     at android.hardware.Camera.autoFocus(Camera.java:1119)
     at ly.img.android.acs.Cam$State$1.onAutoFocus(Cam.java:738)
     at android.hardware.Camera$EventHandler.handleMessage(Camera.java:975)
     at android.os.Handler.dispatchMessage(Handler.java:102)
     at android.os.Looper.loop(Looper.java:212)
     at android.app.ActivityThread.main(ActivityThread.java:5151)
     at java.lang.reflect.Method.invokeNative(Native Method)
     at java.lang.reflect.Method.invoke(Method.java:515)
     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:868)
     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684)
     at dalvik.system.NativeStart.main(Native Method)
```

A similar issue and potential fix can be found [here](https://github.com/dm77/barcodescanner/issues/7)

**Comment by svendvd** [comment]
Fixed in v2.1.1
