### ISSUE TITLE
When applying the filter then App crashes  

### ISSUE THREAD

**Issue by ankurchitranshi** [imgly/imgly-sdk-android-demo#8]
I have implemented the library through "Start Editor Activity standalone. " Step  When aaplying the filter on image then app crashed with error :                                                                                  android.support.v8.renderscript.RSIllegalArgumentException: Attempting to use an object across contexts.
 at android.support.v8.renderscript.ExceptionThunker.convertException(ExceptionThunker.java:24)
at android.support.v8.renderscript.ScriptIntrinsic3DLUTThunker.forEach(ScriptIntrinsic3DLUTThunker.java:72)
 at ly.img.android.sdk.filter.LutColorFilter.renderImage(LutColorFilter.java:264)
 at ly.img.android.sdk.operator.FilterOperation.doOperation(FilterOperation.java:99)
 at ly.img.android.sdk.operator.AbstractOperation.doOperation(AbstractOperation.java:108)
 at ly.img.android.sdk.operator.Operator$BackgroundRunner.run(Operator.java:312)

**Comment by maravilhosinga** [comment]
Same isue, app help

**Comment by divysoni3** [comment]
Write these lines in your gradle:
defaultConfig {
        .
        .
        .
        renderscriptTargetApi 20
        renderscriptSupportModeEnabled true
    }

**Comment by maravilhosinga** [comment]
I already whitten them, the error comes when i want to set a filter.

**Comment by svendvd** [comment]
Sorry for the late replay, now after hours of testing we have an idea!

Did you use Build-SDK 24 *Preview* and Test with an device with lower API Version?

This is not recommended, the min. SDK Version for the SDK 24 *Preview* is offical the API 24 itself.

When you test with an API 24 device the renderscripts run, otherwise on API 23 and lower Devices the app crashes.

Please wait for the Build-SDK 24 release or use Build SDK 23.

**Comment by maravilhosinga** [comment]
Ok, i'll wait

**Comment by svendvd** [comment]
Until google releases Build SDK 24, you can test it on a Android 7 device or the Android 7 emulator.
